In [13]:
import numpy as np

track = np.array([[0,0,0],[0,0,0]], np.int32)
track.shape

track

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [26]:
track_2 = np.full(
    shape=[1,10],
    fill_value=0,
    dtype=np.int
)

print(track_2)

track_3 = track_2 + 1
print(track_3)


[[0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]]


In [39]:
a = np.zeros((5,5))
a[:,4] = 1
a[4,:] = 1
a[0,:] = 1
a[:,0] = 1
    
a


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
b = np.zeros((5,5))

b[:,:] = 1

for i in range(0,5):
    b[0,i] = 2
    b[i,0] = 3
b

array([[3., 2., 2., 2., 2.],
       [3., 1., 1., 1., 1.],
       [3., 1., 1., 1., 1.],
       [3., 1., 1., 1., 1.],
       [3., 1., 1., 1., 1.]])

In [63]:
c = np.zeros((1,5))

c[:,:] = 1
c

for i in range(0,5):
    c[0,i] +=1
    print(c)

[[2. 1. 1. 1. 1.]]
[[2. 2. 1. 1. 1.]]
[[2. 2. 2. 1. 1.]]
[[2. 2. 2. 2. 1.]]
[[2. 2. 2. 2. 2.]]
